package kz.yerbol.domain;
// Generated 28.10.2016 18:30:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private Integer idFaculty;
     private String name;
     private Set specialties = new HashSet(0);

    public Faculty() {
    }

    public Faculty(String name, Set specialties) {
       this.name = name;
       this.specialties = specialties;
    }
   
    public Integer getIdFaculty() {
        return this.idFaculty;
    }
    
    public void setIdFaculty(Integer idFaculty) {
        this.idFaculty = idFaculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSpecialties() {
        return this.specialties;
    }
    
    public void setSpecialties(Set specialties) {
        this.specialties = specialties;
    }

}


