package kz.yerbol.domain;
// Generated 28.10.2016 18:30:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Specialty generated by hbm2java
 */
public class Specialty  implements java.io.Serializable {


     private Integer idspecialty;
     private Faculty faculty;
     private String name;
     private Set students = new HashSet(0);

    public Specialty() {
    }

	
    public Specialty(Faculty faculty, String name) {
        this.faculty = faculty;
        this.name = name;
    }
    public Specialty(Faculty faculty, String name, Set students) {
       this.faculty = faculty;
       this.name = name;
       this.students = students;
    }
   
    public Integer getIdspecialty() {
        return this.idspecialty;
    }
    
    public void setIdspecialty(Integer idspecialty) {
        this.idspecialty = idspecialty;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


